spec:
  containers:
  - name: webserver-simple
    image: docker.io/kostiscodefresh/gitops-simple-app:v1.0
    image: docker.io/kostiscodefresh/gitops-simple-app:v2.0
    ports:
    - containerPort: 8080
